#DATADIR := ../data
#SRCDIR := ./src
LANGUAGE=Rscript
LANGUAGE2=bash

#SEQ_SRC=seq_preprocess.sh
#SEQ_EXE=$(LANGUAGE2) $(SEQ_SRC)

ALIGNMENT_SRC=bams2RDA.R
ALIGNMENT_EXE=$(LANGUAGE) $(ALIGNMENT_SRC)

LVPLOTS_SRC=plotQC_LV.R
LVPLOTS_EXE=$(LANGUAGE) $(LVPLOTS_SRC)

IMPLOTS_SRC=plotQC_IM.R
IMPLOTS_EXE=$(LANGUAGE) $(IMPLOTS_SRC)

EWATPLOTS_SRC=plotQC_EWAT.R
EWATPLOTS_EXE=$(LANGUAGE) $(EWATPLOTS_SRC)

LV_DGEs_SRC=DEG.R
LV_DGEs_EXE=$(LANGUAGE) $(LV_DGEs_SRC)