---
title: "figure1"
author: "Yang Zhang"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load packages
```{r}
library(knitr)
.cran_packages <- c("here", "ggplot2", "dplyr", "tidyverse", "ggpubr", "ggrepel", "lsmeans", "car", "gridExtra", "export")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
# Load packages into session, and print package version
sapply(.cran_packages, require, character.only = TRUE)
```

## load data & setup general plot theme
```{r}
## weight and food related
feeding <- read.csv(file = here("Box/MAN/figure1/", "feeding.csv"), as.is = TRUE)
feeding <- feeding %>%
  dplyr::mutate(vars = factor(Treatment,
                                   levels = c("HFD", "HFD+LXN", "HFD+HXN",
                                              "HFD+TXN", "LFD")))

## measurements
dexa <- read.csv(file = here("Box/MAN/figure1/", "dexa_update.csv"), as.is = TRUE)
dexa <- dexa %>%
  dplyr::mutate(vars = factor(Treatment,
                                   levels = c("HFD", "HFD+LXN", "HFD+HXN",
                                              "HFD+TXN", "LFD")))


## metabolic cage data
profile <- read.csv(file = here("Box/MAN/figure1/", "metabolic_assessment.csv"), as.is = TRUE)
profile$Diet <- as.factor(profile$Diet)
profile$MouseID <- ordered(profile$MouseID)
profile$MouseID <- as.factor(profile$MouseID)
profile <- profile %>%
  dplyr::mutate(vars = factor(Diet,
                                   levels = c("HFD", "HFD+LXN", "HFD+HXN",
                                              "HFD+TXN", "LFD")))


bars <- read.csv(file = here("Box/MAN/figure1/", "bars.csv"), as.is = TRUE)
bars$Diet <- as.factor(bars$Diet)
bars$Cycle <- as.factor(bars$Cycle)
bars$MouseID <- ordered(bars$MouseID)
bars$MouseID <- as.factor(bars$MouseID)

bars <- bars %>%
  dplyr::mutate(vars = factor(Diet,
                                   levels = c("HFD", "HFD+LXN", "HFD+HXN",
                                              "HFD+TXN", "LFD")))


save(feeding, dexa, profile, bars, file = "figure1.rda")
## for ggplot theme & colors
theme_set(theme_bw())
mycolor2 <- c("#0080ff", "#ffa500", "red", "darkgreen", "black")
lines <- c("solid", "solid", "solid", "solid", "dashed")
shapes <- c(24, 4, 15, 25, 1)

### for boxplot
pars <- function(x){
  r <- quantile(x, probs = c(0.10, 0.25, 0.5, 0.75, 0.90))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}
outliers <- function(x){
  subset(x, x < quantile(x, probs = 0.1) | quantile(x, probs = 0.9) < x)
}
```




```{r A to D}
F1A <- ggline(feeding, x = "Week", y = "Weight_gain_percent", group = "vars",
       add = "mean_se", color = "vars", palette = mycolor2,
       ylab = "%", 
       linetype = "vars", shape = "vars", 
       point.size = 2,
       ggtheme = theme_bw())

A <- F1A + scale_linetype_manual(values=c( "solid", "solid", "solid", "solid", "dashed")) + 
    scale_shape_manual(values = shapes) +
    ggtitle("Weekly Weight Gain (%)") +
    theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=10, b=0, l=10)),
          axis.text.y = element_text(size = 15),
          axis.text.x = element_text(size = 18),
          legend.position = "top",
          legend.title = element_text(colour = "white"),
          plot.margin = unit(c(0.5,0.5,0,0.5), "cm"),
          panel.grid = element_blank())

A2 <- A + theme(legend.position = c(0.1, 0.7), legend.background = element_rect())

B <- ggplot(data = total_gained, aes(x = vars, y = Weight_gain_percent, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab(" ") + ylab("%") +
       ggtitle("Cumulative Weight Gained") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.position = "none",
             plot.margin = unit(c(0.5,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

food <- ggline(feeding, x = "Week", y = "Food_Intake_weekly", group = "vars",
       add = "mean_se", color = "vars", palette = mycolor2,
       ylab = "g", 
       linetype = "vars", shape = "vars",
       point.size = 2,
       ggtheme = theme_bw())

C <- food + scale_shape_manual(values = shapes) +
      scale_linetype_manual(values=c("solid", "solid", "solid", "solid", "dashed")) + 
      ggtitle("Weekly Food Intake") +
      theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=10, b=0, l=10)),
            axis.text.y = element_text(size = 15),
            axis.text.x = element_text(size = 18),
            legend.position = "none",
            plot.margin = unit(c(0.5,0.5,0,0.5), "cm"),
            panel.grid = element_blank())

D <- ggplot(data = total_cal, aes(x = vars, y = total, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("kcal") +
  ggtitle("Cumulative Calorie Intake") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.position = "none",
             plot.margin = unit(c(0.5,0.5,0,0.5), "cm"),
             panel.grid = element_blank())
```



```{r E to F}
EE <- ggline(profile, x = "Time", y = "EE", group = "vars",
       add = "mean_se", color = "vars", palette = mycolor2,
       ylab = "kcal/hr", xlab = "", 
       linetype = "vars", shape = "vars",
       point.size = 1.5,
       ggtheme = theme_bw())

EE <- EE + 
    annotate("rect", xmin="Cycle1:17:00-18:00", xmax="Cycle1:05:00-06:00", ymin=0.15, ymax=0.68, 
             alpha=0.2, fill="#5d8aa8") +
    annotate("rect", xmin="Cycle2:17:00-18:00", xmax="Cycle2:05:00-06:00", ymin=0.15, ymax=0.68, 
             alpha=0.2, fill="#5d8aa8")

E <- EE + scale_linetype_manual(values=c("solid", "solid", "solid", "solid", "dashed")) +  
    scale_shape_manual(values = shapes) +
    ggtitle("Energy Expenditure") +
    theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=10, b=0, l=10)),
          axis.text.y = element_text(size = 13),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          legend.title = element_text(size = 15, face = "bold", colour = "white"),
          plot.title = element_text(size = 15),
          legend.text = element_text(size = 15),
          legend.position = "none",
          plot.margin = unit(c(1,0.5,0,0.5), "cm"),
          panel.grid = element_blank())

meanEE <- profile[, 2:4]
meanEE %>% group_by(Diet) %>% summarise(mean = mean(EE), se = sd(EE)/sqrt(n()))

light <- bars %>% filter(Cycle == "1.light")
dark <- bars %>% filter(Cycle == "2.dark")
light %>% group_by(Diet) %>% summarise(mean = mean(AllMeters), se = sd(AllMeters)/sqrt(n()))
dark %>% group_by(Diet) %>% summarise(mean = mean(AllMeters), se = sd(AllMeters)/sqrt(n()))


meterbox <- ggplot(data=bars, aes(x=vars, y=AllMeters, fill=vars)) +
    stat_summary(fun.data = f, geom = "boxplot", position = "dodge") +
    scale_fill_manual(values = alpha(mycolor2, .6)) +
    xlab("") + ylab("meters") +
    facet_grid(~ Cycle) 

Ff <- meterbox + 
    theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=10, b=0, l=0)),
          axis.text.y = element_text(size = 13),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          legend.title = element_text(size = 15, face = "bold", colour = "#303F9F"),
          legend.text = element_text(size = 16),
          strip.background = element_rect(fill = "#536878"),
          legend.position = "none",
          strip.text.x = element_text(size = 15, face = "bold", colour = "white"),
          plot.margin = unit(c(1,0.5,0,0.5), "cm"),
          panel.grid = element_blank())
```


```{r}
feeding$Date <- as.Date(feeding$Date, "%m/%d")
feeding$Treatment <- as.factor(feeding$Treatment)
feeding$Week <- as.factor(feeding$Week)
feeding$ID <- ordered(feeding$ID)
feeding$ID <- as.factor(feeding$ID)

weight_int <- filter(feeding, Date == "2019-02-04")
total_gained <- filter(feeding, Date == "2019-05-28")
total_gained %>% group_by(Treatment) %>% summarise(mean_pct = mean(Weight_gain_percent), 
                                                   mean = mean(Weight), 
                                                   se = sd(Weight_gain_percent)/sqrt(n()))

total_food <- feeding %>% group_by(ID, Treatment) %>% summarise(total = sum(Food_Intake_weekly)) 
total_food %>% group_by(Treatment) %>% summarise(mean = mean(total), 
                                             se = sd(total)/sqrt(n()))


total_cal <- feeding %>% group_by(ID, Treatment) %>% summarise(total = sum(Calories_weekly))
total_cal <- total_cal %>%
  dplyr::mutate(vars = factor(Treatment,
                                   levels = c("HFD", "HFD+LXN", "HFD+HXN",
                                              "HFD+TXN", "LFD")))
total_cal %>% group_by(Treatment) %>% summarise(mean = mean(total), 
                                             se = sd(total)/sqrt(n()))

total_food %>% group_by(Treatment) %>% summarise(mean = mean(total), se = sd(total)/sqrt(n()))
dexa$weight_gained_mass <- total_gained$Weight - weight_int$Weight

profile <- read.csv(file = here("data/phenotype/GF", "metabolic_assessment.csv"), as.is = TRUE)
profile$Diet <- as.factor(profile$Diet)
profile$MouseID <- ordered(profile$MouseID)
profile$MouseID <- as.factor(profile$MouseID)
```

```{r}
Contrasts <- list(
    'TXN vs HFD' = c(-1, 0, 0, 1, 0),
    'HXN vs HFD' = c(-1, 1, 0, 0, 0),
    'LXN vs HFD' = c(-1, 0, 1, 0, 0),
    'LFD vs HFD' = c(-1, 0, 0, 0, 1),
    'TXN vs LFD' = c(0, 0, 0, 1, -1))

model_wg <- lm(Weight_gain_percent ~ Treatment, data = total_gained)
leastsquare_wg <- lsmeans(model_wg, "Treatment")
output_wg <- contrast(leastsquare_wg, Contrasts, adjust = "none")
print(output_wg)

model_fd <- lm(total ~ Treatment, data = total_food)
leastsquare_fd <- lsmeans(model_fd, "Treatment")
output_fd <- contrast(leastsquare_fd, Contrasts, adjust = "none")
print(output_fd)

model_c <- lm(total ~ Treatment, data = total_cal)
leastsquare_c <- lsmeans(model_c, "Treatment")
output_c <- contrast(leastsquare_c, Contrasts, adjust = "none")
print(output_c)

model_fat <- lm(Fat_mass ~ Treatment, data = dexa)
leastsquare_fat <- lsmeans(model_fat, "Treatment")
output_fat <- contrast(leastsquare_fat, Contrasts, adjust = "none")
print(output_fat)

model_m <- lm(mesenteric_wt ~ Treatment, data = dexa)
leastsquare_m <- lsmeans(model_m, "Treatment")
output_m <- contrast(leastsquare_m, Contrasts, adjust = "none")
print(output_m)

model_m <- lm(mesenteric_wt ~ Treatment, data = dexa)
leastsquare_m <- lsmeans(model_m, "Treatment")
output_m <- contrast(leastsquare_m, Contrasts, adjust = "none")
print(output_m)

model_s <- lm(subq_wt ~ Treatment, data = dexa)
leastsquare_s <- lsmeans(model_s, "Treatment")
output_s <- contrast(leastsquare_s, Contrasts, adjust = "none")
print(output_s)

model_b <- lm(bat_wt ~ Treatment, data = dexa)
leastsquare_b <- lsmeans(model_b, "Treatment")
output_b <- contrast(leastsquare_b, Contrasts, adjust = "none")
print(output_b)

model_v <- lm(visceral_wt ~ Treatment, data = dexa)
leastsquare_v <- lsmeans(model_v, "Treatment")
output_v <- contrast(leastsquare_v, Contrasts, adjust = "none")
print(output_v)

model_lv <- lm(liver_wt ~ Treatment, data = dexa)
leastsquare_lv <- lsmeans(model_lv, "Treatment")
output_lv <- contrast(leastsquare_lv, Contrasts, adjust = "none")
print(output_lv)

model_tag <- lm(total_TAG ~ Treatment, data = dexa)
leastsquare_tag <- lsmeans(model_tag, "Treatment")
output_tag <- contrast(leastsquare_tag, Contrasts, adjust = "none")
print(output_tag)

model_lp <- lm(leptin_new ~ Treatment, data = dexa)
leastsquare_lp <- lsmeans(model_lp, "Treatment")
output_lp <- contrast(leastsquare_lp, Contrasts, adjust = "none")
print(output_lp)

model_EE <- lm(EE ~ Diet, data = meanEE)
leastsquare_EE <- lsmeans(model_EE, "Diet")
output_EE <- contrast(leastsquare_EE, Contrasts, adjust = "none")
print(output_EE)

model_lt <- lm(AllMeters ~ Diet, data = light)
leastsquare_lt <- lsmeans(model_lt, "Diet")
output_lt <- contrast(leastsquare_lt, Contrasts, adjust = "none")
print(output_lt)

model_d <- lm(AllMeters ~ Diet, data = dark)
leastsquare_d <- lsmeans(model_d, "Diet")
output_d <- contrast(leastsquare_d, Contrasts, adjust = "none")
print(output_d)
```

```{r G to N}
G <- ggplot(data = dexa, aes(x = vars, y = Fat_mass, fill = vars)) +
     #scale_y_continuous(limits = c(20, 400), breaks = seq(20, 400, by = 40)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("g") +
       ggtitle("Total Fat Mass") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

H <- ggplot(data = dexa, aes(x = vars, y = mesenteric_wt, fill = vars)) +
     #scale_y_continuous(limits = c(20, 400), breaks = seq(20, 400, by = 40)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("g") +
       ggtitle("Mesenteric Fat mass") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

I <- ggplot(data = dexa, aes(x = vars, y = subq_wt, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("g") +
       ggtitle("Subcutaneous Fat mass") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

J <- ggplot(data = dexa, aes(x = vars, y = bat_wt, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("g") +
       ggtitle("Interscapular Brown Fat mass") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

dexa %>% group_by(Treatment) %>% summarise(mean = mean(bat_wt), 
                                             se = sd(bat_wt)/sqrt(n()))

K <- ggplot(data = dexa, aes(x = vars, y = visceral_wt, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("g") +
       ggtitle("Epididymal Fat mass") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

L <- ggplot(data = dexa, aes(x = vars, y = leptin_new, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("ng/mL") +
       ggtitle("Fasting Circulating Leptin") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

M <- ggplot(data = dexa, aes(x = vars, y = liver_wt, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("g") +
       ggtitle("Liver Weight") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

N <- ggplot(data = dexa, aes(x = vars, y = LV_TAG, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("mg/g") +
       ggtitle("Liver TAG") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "bottom",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())

dexa %>% group_by(Treatment) %>% summarise(mean = mean(LV_TAG), 
                                             se = sd(LV_TAG)/sqrt(n()))
```


```{r combine plots}
par1 <- ggarrange(A2, B, align = "hv", 
          widths = c(2.5,1),
          labels = c("A", "B"),
          font.label = list(size = 22, color = "black"),
          nrow = 1, ncol = 2)
par2 <- ggarrange(C, D, align = "hv", 
          widths = c(2.5,1),
          labels = c("C", "D"),
          font.label = list(size = 22, color = "black"),
          nrow = 1, ncol = 2,
          common.legend = TRUE, legend="none")
par3 <- ggarrange(E, Ff, align = "hv", 
          widths = c(2.5,1),
          labels = c("E", "F"),
          font.label = list(size = 22, color = "black"),
          nrow = 1, ncol = 2,
          common.legend = TRUE, legend="none")

partA <- ggarrange(par1, par2, par3, align = "hv",
          heights = c(4,4,4),
          ncol = 1, nrow = 3,
          common.legend = TRUE, legend="bottom")

partB <- ggarrange(G, H, I, J, K, L, M, N, align = "hv",
                   labels = c("G", "H", "I", "J", "K", "L", "M", "N"),
                   font.label = list(size = 22, color = "black"),
          ncol = 4, nrow = 2, heights = c(2,2),
          common.legend = TRUE, legend="bottom")

ggarrange(partA, partB,
          nrow = 2, ncol=1,
          heights = c(4, 2),
          common.legend = TRUE, legend="bottom")

graph2svg(file = here("Box/Gombart_Zhang_Projects/PROJECT_2019_FMT/07. manuscript/", "figure1.svg"), width = 14, height = 18)
graph2pdf(file = here("Box/Gombart_Zhang_Projects/PROJECT_2019_FMT/07. manuscript/", "figure1.pdf"), width = 14, height = 18)
```


```{Figure S2}
L <- ggplot(data = dexa, aes(x = vars, y = total_TAG, fill = vars)) +
       stat_summary(fun.data = pars, geom = "boxplot", position = "dodge") +
       stat_summary(fun.y = outliers, geom = "point") +
       scale_fill_manual(values = alpha(mycolor2, .6)) +
       xlab("") + ylab("mg/dL") +
       ggtitle("Plasma TAG") +
       theme(axis.title.y = element_text(size = 15, margin = margin(t=0, r=5, b=0, l=10)),
             axis.text.y = element_text(size = 13),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank(),
             legend.title = element_text(colour = "white"),
             legend.text = element_text(size = 16),
             legend.position = "none",
             plot.margin = unit(c(1,0.5,0,0.5), "cm"),
             panel.grid = element_blank())
```

