DATADIR := ../data
SRCDIR := ./src
LANGUAGE=Rscript

HOUSEKEEPING_SRC=$(SRCDIR)/housekeeping.R
HOUSEKEEPING_EXE=$(LANGUAGE) $(HOUSEKEEPING_SRC)

PLOTS_SRC=$(SRCDIR)/plots.R
PLOTS_EXE=$(LANGUAGE) $(PLOTS_SRC)

COMBINE_SRC=$(SRCDIR)/combinePlots.R
COMBINE_EXE=$(LANGUAGE) $(COMBINE_SRC)

STAT_SRC=$(SRCDIR)/stats.R
STAT_EXE=$(LANGUAGE) $(STAT_SRC)
